# Generated by Django 5.0.2 on 2024-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
    ]
