# Generated by Django 5.0.2 on 2024-03-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_recommendation_movie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
